<img src="https://github.com/Center-for-Health-Data-Science/PythonTsunami/blob/march2026/figures/tsunami_logo.PNG?raw=1">

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Center-for-Health-Data-Science/PythonTsunami/blob/fall2021/Variables_and_data_types/recap.ipynb)

# Pandas Recap 
**Congratulations!** 

You learned a whole lot of Pandas concepts and skills yesterday! To kick off the final day of of this Python course, we will start by recapping some of the most important Pandas concepts.

## Recap Quiz

Use the next 30 minutes on the quiz below. Work together with the people at your table and discuss your answers. Add code cells and try the code written in the question if you are unsure.

**Question 1**

Consider the data frame below. How do you:

1. Create a new dataframe with only the treatment, age and satisfaction columns?
2. Calculate the mean age?
3. Extract all rows with patients older than 70?
4. Omit rows with missing data?

In [2]:
#defining the dataframe
import pandas as pd

data = [
    ['402109','A','Rigshospitalet',15,68,3],
    ['092070','A','Rigshospitalet',13,74,5],
    ['994082','B','Herlev',27,76,2],
    ['843094','A','Herlev',30,65,5],
    ['369360','B','Rigshospitalet',21,68,5],
    ['688213','B','Rigshospitalet',29,77,3],
    ['197347','A','Herlev',25,65,5],
    ['374793','A','Rigshospitalet', None, 67,5],
    ['759063','B','Rigshospitalet',16,75,4],
    ['121219','B',None,27,68,4],
    ['427898','B','Rigshospitalet',15,74,5]
]

df = pd.DataFrame(data, columns=['patient_id', 'treatment', 'hospital', 'convalescence_days' ,'age', 'satisfaction'])
df

   patient_id treatment        hospital  convalescence_days  age  satisfaction
0      402109         A  Rigshospitalet                15.0   68             3
1      092070         A  Rigshospitalet                13.0   74             5
2      994082         B          Herlev                27.0   76             2
3      843094         A          Herlev                30.0   65             5
4      369360         B  Rigshospitalet                21.0   68             5
5      688213         B  Rigshospitalet                29.0   77             3
6      197347         A          Herlev                25.0   65             5
7      374793         A  Rigshospitalet                 NaN   67             5
8      759063         B  Rigshospitalet                16.0   75             4
9      121219         B            None                27.0   68             4
10     427898         B  Rigshospitalet                15.0   74             5

In [ ]:
#1
new_df = df[['treatment', 'age', 'satisfaction']]
new_df

In [ ]:
#2
df['age'].mean()

In [ ]:
#3
select_rows = df.loc[df['age'] > 70]
select_rows

In [ ]:
#4
df_no_na = df.dropna()

**Question 2**

Consider the data on monkeypox cases in the EU/EEA in the following file: https://opendata.ecdc.europa.eu/monkeypox/casedistribution/csv/data.csv 
How do you:

1. Read the data into pandas?
2. Display all column names?
3. Sort the number of confirmed cases from highest to lowest?
4. Find which country had the maximum number of newly recorded cases on one day?
5. Create new columns for day, month, and year? 
>Hint, you can use str.split() for this.

6. Calculate for Portugal how many confirmed cases there were in total per month and the daily maximum per month?

In [ ]:
#1
url_ecdc_monkeypox = "https://opendata.ecdc.europa.eu/monkeypox/casedistribution/csv/data.csv"
df = pd.read_csv(url_ecdc_monkeypox)

      DateRep CountryExp CountryCode Source  ConfCases
0  2022-04-22    Austria          AT  TESSy          0
1  2022-04-22    Belgium          BE  TESSy          0
2  2022-04-22   Bulgaria          BG  TESSy          0
3  2022-04-22    Croatia          HR  TESSy          0
4  2022-04-22     Cyprus          CY  TESSy          0

In [ ]:
#2
df.columns

      DateRep CountryExp CountryCode Source  ConfCases
0  2022-04-22    Austria          AT  TESSy          0
1  2022-04-22    Belgium          BE  TESSy          0
2  2022-04-22   Bulgaria          BG  TESSy          0
3  2022-04-22    Croatia          HR  TESSy          0
4  2022-04-22     Cyprus          CY  TESSy          0

In [ ]:
#3
df.sort_values(by='ConfCases', ascending=False).head(10)

         DateRep CountryExp CountryCode Source  ConfCases   day month year
2115  2022-07-13      Spain          ES  TESSy        207  2022    07   13
1941  2022-07-07      Spain          ES  TESSy        186  2022    07   07
2376  2022-07-22      Spain          ES  TESSy        178  2022    07   22
2057  2022-07-11      Spain          ES  TESSy        177  2022    07   11
2492  2022-07-26      Spain          ES  TESSy        173  2022    07   26
2086  2022-07-12      Spain          ES  TESSy        164  2022    07   12
2521  2022-07-27      Spain          ES  TESSy        161  2022    07   27
2289  2022-07-19      Spain          ES  TESSy        159  2022    07   19
2695  2022-08-02      Spain          ES  TESSy        159  2022    08   02
2260  2022-07-18      Spain          ES  TESSy        157  2022    07   18

In [ ]:
#4
df.loc[df['ConfCases']==df['ConfCases'].max(), ['DateRep', 'CountryExp', 'ConfCases']]

         DateRep CountryExp  ConfCases
2115  2022-07-13      Spain        207

In [ ]:
#5
df[['year', 'month', 'day']] = df['DateRep'].str.split('-', expand=True)

In [ ]:
#6
df.loc[df['CountryExp']=='Portugal'].groupby(['month', 'year']).agg({'ConfCases':['sum','max']})

           ConfCases
                 sum max
month year
01    2023         0   0
02    2023         0   0
04    2022         3   2
05    2022       183  16
06    2022       277  17
07    2022       272  20
08    2022       156  12
09    2022        40   7
10    2022        10   2
11    2022         2   1
12    2022         2   1